--
-- PostgreSQL database dump
--

-- Dumped from database version 16.3
-- Dumped by pg_dump version 16.3

-- Started on 2024-08-05 19:04:51

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 243 (class 1259 OID 17420)
-- Name: achievement; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.achievement (
    id bigint NOT NULL,
    title character varying(255) NOT NULL,
    description character varying(255)
);


ALTER TABLE public.achievement OWNER TO postgres;

--
-- TOC entry 242 (class 1259 OID 17419)
-- Name: achievement_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.achievement ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.achievement_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 222 (class 1259 OID 17217)
-- Name: category; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.category (
    id bigint NOT NULL,
    name character varying(255) NOT NULL,
    description character varying(255) NOT NULL,
    direction_id bigint NOT NULL
);


ALTER TABLE public.category OWNER TO postgres;

--
-- TOC entry 221 (class 1259 OID 17216)
-- Name: category_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.category ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.category_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 224 (class 1259 OID 17230)
-- Name: course; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.course (
    id bigint NOT NULL,
    name character varying(255) NOT NULL,
    description character varying(255) NOT NULL,
    price bigint NOT NULL,
    is_progress_limited boolean NOT NULL,
    category_id bigint NOT NULL,
    picture_url character varying(255) NOT NULL
);


ALTER TABLE public.course OWNER TO postgres;

--
-- TOC entry 223 (class 1259 OID 17229)
-- Name: course_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.course ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.course_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 241 (class 1259 OID 17379)
-- Name: course_material; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.course_material (
    id bigint NOT NULL,
    course_id bigint NOT NULL,
    material_title character varying(255) NOT NULL,
    material_url character varying(255) NOT NULL
);


ALTER TABLE public.course_material OWNER TO postgres;

--
-- TOC entry 240 (class 1259 OID 17378)
-- Name: course_material_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.course_material ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.course_material_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 220 (class 1259 OID 17209)
-- Name: direction; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.direction (
    id bigint NOT NULL,
    name character varying(255) NOT NULL,
    description character varying(255) NOT NULL
);


ALTER TABLE public.direction OWNER TO postgres;

--
-- TOC entry 219 (class 1259 OID 17208)
-- Name: direction_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.direction ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.direction_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 235 (class 1259 OID 17310)
-- Name: enrolment; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.enrolment (
    course_id bigint NOT NULL,
    student_id bigint NOT NULL,
    enrolment_datetime timestamp without time zone NOT NULL,
    completed_datetime timestamp without time zone,
    is_author boolean NOT NULL
);


ALTER TABLE public.enrolment OWNER TO postgres;

--
-- TOC entry 218 (class 1259 OID 17201)
-- Name: institution; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.institution (
    id bigint NOT NULL,
    name character varying(255) NOT NULL,
    type character varying(255) NOT NULL
);


ALTER TABLE public.institution OWNER TO postgres;

--
-- TOC entry 217 (class 1259 OID 17200)
-- Name: institution_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.institution ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.institution_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 228 (class 1259 OID 17263)
-- Name: lesson; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.lesson (
    id bigint NOT NULL,
    name character varying(255) NOT NULL,
    number integer NOT NULL,
    video_url character varying(255),
    lesson_details character varying(255),
    course_order integer NOT NULL,
    course_id bigint NOT NULL
);


ALTER TABLE public.lesson OWNER TO postgres;

--
-- TOC entry 227 (class 1259 OID 17262)
-- Name: lesson_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.lesson ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.lesson_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 230 (class 1259 OID 17276)
-- Name: quiz; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.quiz (
    id bigint NOT NULL,
    title character varying(255) NOT NULL,
    description character varying(255),
    created_date timestamp without time zone NOT NULL,
    is_active boolean NOT NULL,
    due_date timestamp(6) without time zone,
    reminder_date timestamp(6) without time zone,
    course_order integer NOT NULL,
    course_id bigint NOT NULL
);


ALTER TABLE public.quiz OWNER TO postgres;

--
-- TOC entry 234 (class 1259 OID 17300)
-- Name: quiz_answer; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.quiz_answer (
    id bigint NOT NULL,
    question_id bigint NOT NULL,
    answer_text character varying(255) NOT NULL,
    is_correct boolean NOT NULL
);


ALTER TABLE public.quiz_answer OWNER TO postgres;

--
-- TOC entry 233 (class 1259 OID 17299)
-- Name: quiz_answer_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.quiz_answer ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.quiz_answer_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 229 (class 1259 OID 17275)
-- Name: quiz_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.quiz ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.quiz_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 232 (class 1259 OID 17289)
-- Name: quiz_question; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.quiz_question (
    id bigint NOT NULL,
    quiz_id bigint NOT NULL,
    question_title character varying(255) NOT NULL,
    many_answers boolean NOT NULL
);


ALTER TABLE public.quiz_question OWNER TO postgres;

--
-- TOC entry 231 (class 1259 OID 17288)
-- Name: quiz_question_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.quiz_question ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.quiz_question_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 239 (class 1259 OID 17356)
-- Name: review; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.review (
    id bigint NOT NULL,
    user_id bigint NOT NULL,
    course_id bigint NOT NULL,
    created_date timestamp without time zone NOT NULL,
    score integer NOT NULL,
    review_text character varying(255) NOT NULL
);


ALTER TABLE public.review OWNER TO postgres;

--
-- TOC entry 238 (class 1259 OID 17355)
-- Name: review_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.review ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.review_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 216 (class 1259 OID 17195)
-- Name: role; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.role (
    id bigint NOT NULL,
    name character varying(255) NOT NULL
);


ALTER TABLE public.role OWNER TO postgres;

--
-- TOC entry 215 (class 1259 OID 17194)
-- Name: role_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.role ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.role_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 226 (class 1259 OID 17243)
-- Name: site_user; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.site_user (
    id bigint NOT NULL,
    email_address character varying(255) NOT NULL,
    password character varying(255) NOT NULL,
    signup_date date NOT NULL,
    role_id bigint NOT NULL,
    institution_id bigint NOT NULL,
    login character varying(255) NOT NULL
);


ALTER TABLE public.site_user OWNER TO postgres;

--
-- TOC entry 225 (class 1259 OID 17242)
-- Name: site_user_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.site_user ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.site_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 236 (class 1259 OID 17325)
-- Name: student_lesson; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.student_lesson (
    student_id bigint NOT NULL,
    lesson_id bigint NOT NULL,
    completed_datetime timestamp without time zone NOT NULL
);


ALTER TABLE public.student_lesson OWNER TO postgres;

--
-- TOC entry 237 (class 1259 OID 17340)
-- Name: student_quiz_attempt; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.student_quiz_attempt (
    student_id bigint NOT NULL,
    quiz_id bigint NOT NULL,
    attempt_datetime timestamp without time zone NOT NULL,
    score_achieved integer NOT NULL
);


ALTER TABLE public.student_quiz_attempt OWNER TO postgres;

--
-- TOC entry 244 (class 1259 OID 17427)
-- Name: user_achievement; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.user_achievement (
    user_id bigint NOT NULL,
    achievement_id bigint NOT NULL,
    date_achieved date NOT NULL
);


ALTER TABLE public.user_achievement OWNER TO postgres;

--
-- TOC entry 4746 (class 2606 OID 17426)
-- Name: achievement achievement_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.achievement
    ADD CONSTRAINT achievement_pkey PRIMARY KEY (id);


--
-- TOC entry 4717 (class 2606 OID 17223)
-- Name: category category_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.category
    ADD CONSTRAINT category_pkey PRIMARY KEY (id);


--
-- TOC entry 4744 (class 2606 OID 17385)
-- Name: course_material course_material_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.course_material
    ADD CONSTRAINT course_material_pkey PRIMARY KEY (id);


--
-- TOC entry 4719 (class 2606 OID 17236)
-- Name: course course_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.course
    ADD CONSTRAINT course_pkey PRIMARY KEY (id);


--
-- TOC entry 4715 (class 2606 OID 17215)
-- Name: direction direction_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.direction
    ADD CONSTRAINT direction_pkey PRIMARY KEY (id);


--
-- TOC entry 4734 (class 2606 OID 17314)
-- Name: enrolment enrolment_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.enrolment
    ADD CONSTRAINT enrolment_pkey PRIMARY KEY (course_id, student_id);


--
-- TOC entry 4713 (class 2606 OID 17207)
-- Name: institution institution_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.institution
    ADD CONSTRAINT institution_pkey PRIMARY KEY (id);


--
-- TOC entry 4726 (class 2606 OID 17269)
-- Name: lesson lesson_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.lesson
    ADD CONSTRAINT lesson_pkey PRIMARY KEY (id);


--
-- TOC entry 4732 (class 2606 OID 17304)
-- Name: quiz_answer quiz_answer_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.quiz_answer
    ADD CONSTRAINT quiz_answer_pkey PRIMARY KEY (id);


--
-- TOC entry 4728 (class 2606 OID 17282)
-- Name: quiz quiz_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.quiz
    ADD CONSTRAINT quiz_pkey PRIMARY KEY (id);


--
-- TOC entry 4730 (class 2606 OID 17293)
-- Name: quiz_question quiz_question_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.quiz_question
    ADD CONSTRAINT quiz_question_pkey PRIMARY KEY (id);


--
-- TOC entry 4742 (class 2606 OID 17362)
-- Name: review review_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.review
    ADD CONSTRAINT review_pkey PRIMARY KEY (id);


--
-- TOC entry 4711 (class 2606 OID 17199)
-- Name: role role_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.role
    ADD CONSTRAINT role_pkey PRIMARY KEY (id);


--
-- TOC entry 4722 (class 2606 OID 17251)
-- Name: site_user site_user_email_address_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.site_user
    ADD CONSTRAINT site_user_email_address_key UNIQUE (email_address);


--
-- TOC entry 4724 (class 2606 OID 17249)
-- Name: site_user site_user_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.site_user
    ADD CONSTRAINT site_user_pkey PRIMARY KEY (id);


--
-- TOC entry 4738 (class 2606 OID 17329)
-- Name: student_lesson student_lesson_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.student_lesson
    ADD CONSTRAINT student_lesson_pkey PRIMARY KEY (student_id, lesson_id);


--
-- TOC entry 4740 (class 2606 OID 17344)
-- Name: student_quiz_attempt student_quiz_attempt_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.student_quiz_attempt
    ADD CONSTRAINT student_quiz_attempt_pkey PRIMARY KEY (student_id, quiz_id, attempt_datetime);


--
-- TOC entry 4748 (class 2606 OID 17431)
-- Name: user_achievement user_achievement_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_achievement
    ADD CONSTRAINT user_achievement_pkey PRIMARY KEY (user_id, achievement_id);


--
-- TOC entry 4735 (class 1259 OID 17375)
-- Name: idx_enrolment_course; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_enrolment_course ON public.enrolment USING btree (course_id);


--
-- TOC entry 4736 (class 1259 OID 17374)
-- Name: idx_enrolment_student; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_enrolment_student ON public.enrolment USING btree (student_id);


--
-- TOC entry 4720 (class 1259 OID 17373)
-- Name: idx_site_user_email; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_site_user_email ON public.site_user USING btree (email_address);


--
-- TOC entry 4749 (class 2606 OID 17224)
-- Name: category category_direction_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.category
    ADD CONSTRAINT category_direction_id_fkey FOREIGN KEY (direction_id) REFERENCES public.direction(id) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- TOC entry 4750 (class 2606 OID 17237)
-- Name: course course_category_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.course
    ADD CONSTRAINT course_category_id_fkey FOREIGN KEY (category_id) REFERENCES public.category(id) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- TOC entry 4765 (class 2606 OID 17386)
-- Name: course_material course_material_course_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.course_material
    ADD CONSTRAINT course_material_course_id_fkey FOREIGN KEY (course_id) REFERENCES public.course(id) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- TOC entry 4757 (class 2606 OID 17315)
-- Name: enrolment enrolment_course_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.enrolment
    ADD CONSTRAINT enrolment_course_id_fkey FOREIGN KEY (course_id) REFERENCES public.course(id) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- TOC entry 4758 (class 2606 OID 17320)
-- Name: enrolment enrolment_student_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.enrolment
    ADD CONSTRAINT enrolment_student_id_fkey FOREIGN KEY (student_id) REFERENCES public.site_user(id) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- TOC entry 4753 (class 2606 OID 17270)
-- Name: lesson lesson_course_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.lesson
    ADD CONSTRAINT lesson_course_id_fkey FOREIGN KEY (course_id) REFERENCES public.course(id) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- TOC entry 4756 (class 2606 OID 17305)
-- Name: quiz_answer quiz_answer_question_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.quiz_answer
    ADD CONSTRAINT quiz_answer_question_id_fkey FOREIGN KEY (question_id) REFERENCES public.quiz_question(id) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- TOC entry 4754 (class 2606 OID 17283)
-- Name: quiz quiz_course_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.quiz
    ADD CONSTRAINT quiz_course_id_fkey FOREIGN KEY (course_id) REFERENCES public.course(id) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- TOC entry 4755 (class 2606 OID 17294)
-- Name: quiz_question quiz_question_quiz_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.quiz_question
    ADD CONSTRAINT quiz_question_quiz_id_fkey FOREIGN KEY (quiz_id) REFERENCES public.quiz(id) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- TOC entry 4763 (class 2606 OID 17368)
-- Name: review review_course_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.review
    ADD CONSTRAINT review_course_id_fkey FOREIGN KEY (course_id) REFERENCES public.course(id) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- TOC entry 4764 (class 2606 OID 17363)
-- Name: review review_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.review
    ADD CONSTRAINT review_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.site_user(id) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- TOC entry 4751 (class 2606 OID 17257)
-- Name: site_user site_user_institution_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.site_user
    ADD CONSTRAINT site_user_institution_id_fkey FOREIGN KEY (institution_id) REFERENCES public.institution(id) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- TOC entry 4752 (class 2606 OID 17252)
-- Name: site_user site_user_role_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.site_user
    ADD CONSTRAINT site_user_role_id_fkey FOREIGN KEY (role_id) REFERENCES public.role(id) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- TOC entry 4759 (class 2606 OID 17335)
-- Name: student_lesson student_lesson_lesson_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.student_lesson
    ADD CONSTRAINT student_lesson_lesson_id_fkey FOREIGN KEY (lesson_id) REFERENCES public.lesson(id) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- TOC entry 4760 (class 2606 OID 17330)
-- Name: student_lesson student_lesson_student_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.student_lesson
    ADD CONSTRAINT student_lesson_student_id_fkey FOREIGN KEY (student_id) REFERENCES public.site_user(id) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- TOC entry 4761 (class 2606 OID 17350)
-- Name: student_quiz_attempt student_quiz_attempt_quiz_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.student_quiz_attempt
    ADD CONSTRAINT student_quiz_attempt_quiz_id_fkey FOREIGN KEY (quiz_id) REFERENCES public.quiz(id) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- TOC entry 4762 (class 2606 OID 17345)
-- Name: student_quiz_attempt student_quiz_attempt_student_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.student_quiz_attempt
    ADD CONSTRAINT student_quiz_attempt_student_id_fkey FOREIGN KEY (student_id) REFERENCES public.site_user(id) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- TOC entry 4766 (class 2606 OID 17437)
-- Name: user_achievement user_achievement_achievement_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_achievement
    ADD CONSTRAINT user_achievement_achievement_id_fkey FOREIGN KEY (achievement_id) REFERENCES public.achievement(id) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- TOC entry 4767 (class 2606 OID 17432)
-- Name: user_achievement user_achievement_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_achievement
    ADD CONSTRAINT user_achievement_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.site_user(id) ON UPDATE CASCADE ON DELETE CASCADE;


-- Completed on 2024-08-05 19:04:52

--
-- PostgreSQL database dump complete
--

